import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const imageGenerationModel = 'gemini-2.5-flash-image';
const textGenerationModel = 'gemini-2.5-flash';

interface ImageInput {
  base64: string;
  mimeType: string;
}

export const generateDescriptionFromImage = async (image: ImageInput): Promise<string> => {
  try {
    const descriptionPrompt = "Analyze this rough, monochrome sketch. Describe the basic composition and key elements you see in a concise, descriptive sentence. This description will be used as a prompt for another AI to generate a detailed storyboard. For example, if you see a circle in the middle with a line below it, describe it as 'A central circular object positioned above a horizontal base.'";

    const response = await ai.models.generateContent({
      model: textGenerationModel,
      contents: {
        parts: [
          {
            inlineData: {
              data: image.base64,
              mimeType: image.mimeType,
            },
          },
          {
            text: descriptionPrompt,
          },
        ],
      },
    });

    const description = response.text;
    if (!description) {
      throw new Error("No description was generated by the API.");
    }
    return description.trim();
  } catch (error) {
    console.error("Error generating description with Gemini API:", error);
    throw new Error("Failed to generate description from the image.");
  }
};

const BASE_PROMPT = `You are a master storyboard artist for a major film studio. Your task is to translate a director's vision into a single, powerful storyboard frame. {STYLE_INSTRUCTIONS} You will be given two inputs: 1. A rough, hand-drawn sketch from the director, which you MUST use for the core composition, object placement, and camera angle. 2. A text prompt describing the scene's details, mood, and action. The output MUST be a monochrome (black and white) image. Focus on cinematic storytelling: clear character poses, dramatic lighting, and a strong sense of mood. Do not create a photorealistic image. This is a sketch meant to convey an idea quickly and effectively. Create the following scene: {prompt}`;


const generateSingleImage = async (prompt: string, image: ImageInput, stylePrompt: string): Promise<string> => {
    const fullPrompt = BASE_PROMPT
      .replace('{STYLE_INSTRUCTIONS}', stylePrompt)
      .replace('{prompt}', prompt);

    const response = await ai.models.generateContent({
        model: imageGenerationModel,
        contents: {
            parts: [
                {
                    inlineData: {
                        data: image.base64,
                        mimeType: image.mimeType,
                    },
                },
                {
                    text: fullPrompt,
                },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
    }

    throw new Error("No image data found in the API response.");
};


export const editImageWithPrompt = async (originalImage: ImageInput, editInstruction: string, stylePrompt: string): Promise<string> => {
  try {
    const editPrompt = `Based on the provided image, apply the following edit: "${editInstruction}". Maintain the original artistic style which is defined as: "${stylePrompt}". Ensure the edit integrates seamlessly with the existing composition and mood.`;

    const response = await ai.models.generateContent({
      model: imageGenerationModel,
      contents: {
        parts: [
          {
            inlineData: {
              data: originalImage.base64,
              mimeType: originalImage.mimeType,
            },
          },
          { text: editPrompt },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No edited image data found in the API response.");
  } catch (error) {
    console.error("Error editing image with Gemini API:", error);
    throw new Error("Failed to edit the image.");
  }
};

export const generateStoryboards = async (prompt: string, image: ImageInput, stylePrompt: string): Promise<string[]> => {
  try {
    const generationPromises = [
      generateSingleImage(prompt, image, stylePrompt),
      generateSingleImage(prompt, image, stylePrompt),
      generateSingleImage(prompt, image, stylePrompt),
      generateSingleImage(prompt, image, stylePrompt),
    ];

    const results = await Promise.all(generationPromises);
    return results;
  } catch (error) {
    console.error("Error generating storyboards with Gemini API:", error);
    throw new Error("Failed to generate images from the API.");
  }
};