import type { VercelRequest, VercelResponse } from '@vercel/node';

const QWEN_API_KEY = process.env.QWEN_API_KEY;
const QWEN_VL_ENDPOINT = 'https://dashscope-intl.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation';

if (!QWEN_API_KEY) {
  throw new Error("QWEN_API_KEY environment variable not set");
}

const descriptionPrompt = `Analyze this rough, monochrome sketch. Describe the basic composition and key elements you see in a concise, descriptive sentence (max 2-3 sentences).

Focus on:
- Main subjects/characters and their positions
- Camera angle and framing
- Key objects or props
- Spatial relationships

This description will be used to generate a detailed storyboard, so be precise about composition.`;

interface QwenVLResponse {
  output: {
    choices: Array<{
      message: {
        content: Array<{
          text: string;
        }>;
      };
    }>;
  };
  request_id: string;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  console.log('[generate-description] Request received');

  if (req.method !== 'POST') {
    console.log('[generate-description] Method not allowed:', req.method);
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { image } = req.body;

    console.log('[generate-description] Image size:', image?.base64?.length || 0);

    if (!image || !image.base64 || !image.mimeType) {
      console.log('[generate-description] Invalid image data');
      return res.status(400).json({ error: 'Invalid image data' });
    }

    const payload = {
      model: 'qwen-vl-plus',
      input: {
        messages: [
          {
            role: 'user',
            content: [
              { image: `data:${image.mimeType};base64,${image.base64}` },
              { text: descriptionPrompt }
            ]
          }
        ]
      }
    };

    const response = await fetch(QWEN_VL_ENDPOINT, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${QWEN_API_KEY}`
      },
      body: JSON.stringify(payload)
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('[generate-description] Qwen VL API error:', errorText);
      throw new Error(`Qwen VL API error (${response.status}): ${errorText}`);
    }

    const data: QwenVLResponse = await response.json();
    const description = data.output?.choices?.[0]?.message?.content?.[0]?.text;

    if (!description) {
      console.log('[generate-description] No description generated');
      throw new Error("No description was generated by Qwen VL API");
    }

    console.log('[generate-description] Success! Description length:', description.length);
    return res.status(200).json({ description: description.trim() });
  } catch (error) {
    console.error("[generate-description] Error:", error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    console.error("[generate-description] Error details:", errorMessage);
    return res.status(500).json({
      error: "Failed to generate description from the image.",
      details: errorMessage
    });
  }
}
