import { GoogleGenAI } from "@google/genai";
import type { VercelRequest, VercelResponse } from '@vercel/node';

const API_KEY = process.env.GEMINI_API_KEY;

if (!API_KEY) {
  throw new Error("GEMINI_API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });
const textGenerationModel = 'gemini-2.5-flash';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  console.log('[generate-description] Request received');

  if (req.method !== 'POST') {
    console.log('[generate-description] Method not allowed:', req.method);
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { image } = req.body;

    console.log('[generate-description] Image size:', image?.base64?.length || 0);

    if (!image || !image.base64 || !image.mimeType) {
      console.log('[generate-description] Invalid image data');
      return res.status(400).json({ error: 'Invalid image data' });
    }

    const descriptionPrompt = "Analyze this rough, monochrome sketch. Describe the basic composition and key elements you see in a concise, descriptive sentence. This description will be used as a prompt for another AI to generate a detailed storyboard. For example, if you see a circle in the middle with a line below it, describe it as 'A central circular object positioned above a horizontal base.'";

    const response = await ai.models.generateContent({
      model: textGenerationModel,
      contents: {
        parts: [
          {
            inlineData: {
              data: image.base64,
              mimeType: image.mimeType,
            },
          },
          {
            text: descriptionPrompt,
          },
        ],
      },
    });

    const description = response.text;
    if (!description) {
      console.log('[generate-description] No description generated');
      throw new Error("No description was generated by the API.");
    }

    console.log('[generate-description] Success! Description length:', description.length);
    return res.status(200).json({ description: description.trim() });
  } catch (error) {
    console.error("[generate-description] Error:", error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    console.error("[generate-description] Error details:", errorMessage);
    return res.status(500).json({
      error: "Failed to generate description from the image.",
      details: errorMessage
    });
  }
}
